server:
  port: 8500

spring:
  application:
    name: ui-service
    
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8100/eureka/}
