server:
  port: 8100
  
spring:
  application:
    name: eureka-server
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8100/eureka/}